version: '3.8'
services:
  postgres:
    image: postgres:12
    container_name: daily_diet
    environment:
      POSTGRES_DB: daily_diet
      POSTGRES_USER: daily_diet
      POSTGRES_PASSWORD: daily_diet123
    network_mode: bridge
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local
